package com.aegisdispatch.model;

public final class Enums {
  private Enums() {}
  public enum AmbulanceStatus { AVAILABLE, RESERVED, DISPATCHED, EN_ROUTE_TO_PATIENT, ARRIVED_AT_SCENE, PATIENT_ONBOARD, EN_ROUTE_TO_HOSPITAL, AT_HOSPITAL, OUT_OF_SERVICE }
  public enum EmergencyStatus { CREATED, PENDING_DISPATCH, DISPATCHED, AMBULANCE_ACCEPTED, EN_ROUTE_TO_SCENE, ARRIVED_AT_SCENE, PATIENT_ONBOARD, EN_ROUTE_TO_HOSPITAL, ARRIVED_AT_HOSPITAL, PATIENT_HANDED_OVER, COMPLETED, CANCELLED, NO_AMBULANCE_AVAILABLE, DECLINED, REASSIGNED }
  public enum Priority { CRITICAL, HIGH, MEDIUM, LOW }
}
